# coding: utf-8

"""
    OPIF Manager API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class FileUploadStats(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_date': 'date',
        'file_upload_count': 'int',
        'file_error_count': 'int'
    }

    attribute_map = {
        '_date': 'date',
        'file_upload_count': 'fileUploadCount',
        'file_error_count': 'fileErrorCount'
    }

    def __init__(self, _date=None, file_upload_count=None, file_error_count=None):  # noqa: E501
        """FileUploadStats - a model defined in Swagger"""  # noqa: E501
        self.__date = None
        self._file_upload_count = None
        self._file_error_count = None
        self.discriminator = None
        if _date is not None:
            self._date = _date
        if file_upload_count is not None:
            self.file_upload_count = file_upload_count
        if file_error_count is not None:
            self.file_error_count = file_error_count

    @property
    def _date(self):
        """Gets the _date of this FileUploadStats.  # noqa: E501


        :return: The _date of this FileUploadStats.  # noqa: E501
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this FileUploadStats.


        :param _date: The _date of this FileUploadStats.  # noqa: E501
        :type: date
        """

        self.__date = _date

    @property
    def file_upload_count(self):
        """Gets the file_upload_count of this FileUploadStats.  # noqa: E501


        :return: The file_upload_count of this FileUploadStats.  # noqa: E501
        :rtype: int
        """
        return self._file_upload_count

    @file_upload_count.setter
    def file_upload_count(self, file_upload_count):
        """Sets the file_upload_count of this FileUploadStats.


        :param file_upload_count: The file_upload_count of this FileUploadStats.  # noqa: E501
        :type: int
        """

        self._file_upload_count = file_upload_count

    @property
    def file_error_count(self):
        """Gets the file_error_count of this FileUploadStats.  # noqa: E501


        :return: The file_error_count of this FileUploadStats.  # noqa: E501
        :rtype: int
        """
        return self._file_error_count

    @file_error_count.setter
    def file_error_count(self, file_error_count):
        """Sets the file_error_count of this FileUploadStats.


        :param file_error_count: The file_error_count of this FileUploadStats.  # noqa: E501
        :type: int
        """

        self._file_error_count = file_error_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FileUploadStats, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FileUploadStats):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
