# coding: utf-8

"""
    OPIF Manager API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.search_api import SearchApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = api.search_api.SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_key_search_key_format_get(self):
        """Test case for search_key_search_key_format_get

        Search for files and folders  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
