# coding: utf-8

"""
    OPIF Manager API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.folder_api import FolderApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFolderApi(unittest.TestCase):
    """FolderApi unit test stubs"""

    def setUp(self):
        self.api = api.folder_api.FolderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_folder_create_format_post(self):
        """Test case for folder_create_format_post

        Create new folder  # noqa: E501
        """
        pass

    def test_folder_delete_folder_id_entity_id_service_code_format_delete(self):
        """Test case for folder_delete_folder_id_entity_id_service_code_format_delete

        Delete Folder  # noqa: E501
        """
        pass

    def test_folder_history_count_jsonentity_identity_id_get(self):
        """Test case for folder_history_count_jsonentity_identity_id_get

        Count of Folder changes  # noqa: E501
        """
        pass

    def test_folder_history_format_get(self):
        """Test case for folder_history_format_get

        Folder changes list  # noqa: E501
        """
        pass

    def test_folder_id_folder_id_format_get(self):
        """Test case for folder_id_folder_id_format_get

        Get Subfolder and files  # noqa: E501
        """
        pass

    def test_folder_more_public_folders_format_get(self):
        """Test case for folder_more_public_folders_format_get

        Get More Public Folders   # noqa: E501
        """
        pass

    def test_folder_parent_folders_format_get(self):
        """Test case for folder_parent_folders_format_get

        Get parent folders  # noqa: E501
        """
        pass

    def test_folder_path_format_get(self):
        """Test case for folder_path_format_get

        Get Folder for specified path.  # noqa: E501
        """
        pass

    def test_folder_purge_folder_id_entity_id_service_code_format_delete(self):
        """Test case for folder_purge_folder_id_entity_id_service_code_format_delete

        Purge Folder  # noqa: E501
        """
        pass

    def test_folder_rename_format_put(self):
        """Test case for folder_rename_format_put

        Rename Folder  # noqa: E501
        """
        pass

    def test_folder_restore_format_put(self):
        """Test case for folder_restore_format_put

        Restore Folder  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
