# coding: utf-8

"""
    OPIF Manager API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.download_api import DownloadApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDownloadApi(unittest.TestCase):
    """DownloadApi unit test stubs"""

    def setUp(self):
        self.api = api.download_api.DownloadApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_folder_id_file_manager_id_pdf_get(self):
        """Test case for download_folder_id_file_manager_id_pdf_get

        Dowload converted File  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
