# coding: utf-8

"""
    OPIF Manager API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.file_api import FileApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFileApi(unittest.TestCase):
    """FileApi unit test stubs"""

    def setUp(self):
        self.api = api.file_api.FileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_entity_logo_upload_post(self):
        """Test case for entity_logo_upload_post

        Upload logo  # noqa: E501
        """
        pass

    def test_file_history_count_jsonentity_identity_id_get(self):
        """Test case for file_history_count_jsonentity_identity_id_get

        Count of Files changes  # noqa: E501
        """
        pass

    def test_file_history_format_get(self):
        """Test case for file_history_format_get

        List changed files  # noqa: E501
        """
        pass

    def test_file_id_file_id_format_get(self):
        """Test case for file_id_file_id_format_get

        Get File Details  # noqa: E501
        """
        pass

    def test_file_move_format_put(self):
        """Test case for file_move_format_put

        Move File   # noqa: E501
        """
        pass

    def test_file_purge_file_id_entity_id_service_code_format_delete(self):
        """Test case for file_purge_file_id_entity_id_service_code_format_delete

        Purge File  # noqa: E501
        """
        pass

    def test_file_remove_file_id_entity_id_service_code_format_delete(self):
        """Test case for file_remove_file_id_entity_id_service_code_format_delete

        Remove File  # noqa: E501
        """
        pass

    def test_file_rename_format_put(self):
        """Test case for file_rename_format_put

        Rename File   # noqa: E501
        """
        pass

    def test_file_restore_format_put(self):
        """Test case for file_restore_format_put

        Restore File   # noqa: E501
        """
        pass

    def test_file_upload_format_post(self):
        """Test case for file_upload_format_post

        Upload file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
