# coding: utf-8

"""
    OPIF Manager API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.access_token_post import AccessTokenPost  # noqa: E501
from swagger_client.rest import ApiException


class TestAccessTokenPost(unittest.TestCase):
    """AccessTokenPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessTokenPost(self):
        """Test AccessTokenPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.access_token_post.AccessTokenPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
