wandb_version: 1

_wandb:
    desc: null
    value:
    cli_version: 0.8.31
    code_path: ./train_basic.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
batch_size:
    desc: null
    value: 64
dataset:
    desc: null
    value: mini_training
max_len_input:
    desc: null
    value: 13678
max_len_output:
    desc: null
    value: 12
model_type:
    desc: null
    value: word seq2seq
num_epochs:
    desc: null
    value: 75
num_train:
    desc: null
    value: 4510
num_units:
    desc: null
    value: 200
optimizer:
    desc: null
    value: rmsprop
vocab_size:
  desc: null
  value: 25157
