# coding: utf-8

"""
    OPIF Service Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class ContactUpdatesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def contact_update_json_post(self, body, **kwargs):  # noqa: E501
        """Specify contactType as \"MS\" for Main Studio Contact and \"CC\" for Closed Caption Contact.  # noqa: E501

        Specify contactType as \"MS\" for Main Studio Contact and \"CC\" for Closed Caption Contact. Allowed values for contactSourceServiceCode are \"TV\", \"AM\" and \"FM\" for Main Studio Contact and \"TV\" for Closed Captions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.contact_update_json_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param MainStudioClosedCaptionUpdate body: Specify contactType as "MS" for Main Studio Contact and "CC" for Closed Caption Contact. Allowed values for contactSourceServiceCode are "TV", "AM" and "FM" for Main Studio Contact and "TV" for Closed Captions. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.contact_update_json_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.contact_update_json_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def contact_update_json_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """Specify contactType as \"MS\" for Main Studio Contact and \"CC\" for Closed Caption Contact.  # noqa: E501

        Specify contactType as \"MS\" for Main Studio Contact and \"CC\" for Closed Caption Contact. Allowed values for contactSourceServiceCode are \"TV\", \"AM\" and \"FM\" for Main Studio Contact and \"TV\" for Closed Captions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.contact_update_json_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param MainStudioClosedCaptionUpdate body: Specify contactType as "MS" for Main Studio Contact and "CC" for Closed Caption Contact. Allowed values for contactSourceServiceCode are "TV", "AM" and "FM" for Main Studio Contact and "TV" for Closed Captions. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method contact_update_json_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `contact_update_json_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            'contact/update.json', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
