# coding: utf-8

"""
    OPIF Service Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class DbsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def dbs_eeo_facility_facility_id_format_get(self, facility_id, format, **kwargs):  # noqa: E501
        """DBS EEO  # noqa: E501

        DBS EEO  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.dbs_eeo_facility_facility_id_format_get(facility_id, format, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str facility_id: facilityID (required)
        :param str format: json,  xml (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.dbs_eeo_facility_facility_id_format_get_with_http_info(facility_id, format, **kwargs)  # noqa: E501
        else:
            (data) = self.dbs_eeo_facility_facility_id_format_get_with_http_info(facility_id, format, **kwargs)  # noqa: E501
            return data

    def dbs_eeo_facility_facility_id_format_get_with_http_info(self, facility_id, format, **kwargs):  # noqa: E501
        """DBS EEO  # noqa: E501

        DBS EEO  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.dbs_eeo_facility_facility_id_format_get_with_http_info(facility_id, format, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str facility_id: facilityID (required)
        :param str format: json,  xml (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['facility_id', 'format']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method dbs_eeo_facility_facility_id_format_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'facility_id' is set
        if ('facility_id' not in params or
                params['facility_id'] is None):
            raise ValueError("Missing the required parameter `facility_id` when calling `dbs_eeo_facility_facility_id_format_get`")  # noqa: E501
        # verify the required parameter 'format' is set
        if ('format' not in params or
                params['format'] is None):
            raise ValueError("Missing the required parameter `format` when calling `dbs_eeo_facility_facility_id_format_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'facility_id' in params:
            path_params['facilityID'] = params['facility_id']  # noqa: E501
        if 'format' in params:
            path_params['format'] = params['format']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/dbs/eeo/facility/{facilityID}.{format}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def dbs_frn_frn_format_get(self, frn, format, **kwargs):  # noqa: E501
        """DBS Entity Details  # noqa: E501

        DBS Entity Details  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.dbs_frn_frn_format_get(frn, format, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str frn: frn - length of 10 digits (required)
        :param str format: json,  xml (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.dbs_frn_frn_format_get_with_http_info(frn, format, **kwargs)  # noqa: E501
        else:
            (data) = self.dbs_frn_frn_format_get_with_http_info(frn, format, **kwargs)  # noqa: E501
            return data

    def dbs_frn_frn_format_get_with_http_info(self, frn, format, **kwargs):  # noqa: E501
        """DBS Entity Details  # noqa: E501

        DBS Entity Details  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.dbs_frn_frn_format_get_with_http_info(frn, format, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str frn: frn - length of 10 digits (required)
        :param str format: json,  xml (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['frn', 'format']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method dbs_frn_frn_format_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'frn' is set
        if ('frn' not in params or
                params['frn'] is None):
            raise ValueError("Missing the required parameter `frn` when calling `dbs_frn_frn_format_get`")  # noqa: E501
        # verify the required parameter 'format' is set
        if ('format' not in params or
                params['format'] is None):
            raise ValueError("Missing the required parameter `format` when calling `dbs_frn_frn_format_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'frn' in params:
            path_params['frn'] = params['frn']  # noqa: E501
        if 'format' in params:
            path_params['format'] = params['format']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/dbs/frn/{frn}.{format}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def dbs_getall_format_get(self, format, **kwargs):  # noqa: E501
        """Get All  # noqa: E501

        Get All  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.dbs_getall_format_get(format, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str format: json,  xml (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.dbs_getall_format_get_with_http_info(format, **kwargs)  # noqa: E501
        else:
            (data) = self.dbs_getall_format_get_with_http_info(format, **kwargs)  # noqa: E501
            return data

    def dbs_getall_format_get_with_http_info(self, format, **kwargs):  # noqa: E501
        """Get All  # noqa: E501

        Get All  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.dbs_getall_format_get_with_http_info(format, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str format: json,  xml (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['format']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method dbs_getall_format_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'format' is set
        if ('format' not in params or
                params['format'] is None):
            raise ValueError("Missing the required parameter `format` when calling `dbs_getall_format_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'format' in params:
            path_params['format'] = params['format']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/dbs/getall.{format}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def dbs_licensee_address_update_json_post(self, body, **kwargs):  # noqa: E501
        """Update licensee address  # noqa: E501

        Update licensee address  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.dbs_licensee_address_update_json_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param LicenseeAddressUpdatePost body: Create address post data body. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.dbs_licensee_address_update_json_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.dbs_licensee_address_update_json_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def dbs_licensee_address_update_json_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """Update licensee address  # noqa: E501

        Update licensee address  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.dbs_licensee_address_update_json_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param LicenseeAddressUpdatePost body: Create address post data body. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method dbs_licensee_address_update_json_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `dbs_licensee_address_update_json_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/dbs/licenseeAddress/update.json', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
