# coding: utf-8

"""
    OPIF File Search

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class SearchApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def qkeywordsoffsetoorderffilters_get(self, keyword, offset, order, filters, **kwargs):  # noqa: E501
        """Search File Names  # noqa: E501

        Search file names of the uploaded documents in the OPIF system.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.qkeywordsoffsetoorderffilters_get(keyword, offset, order, filters, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str keyword: Keyword. (required)
        :param str offset: Search results starting number. (required)
        :param str order: Sorting parameter. (required)
        :param str filters: JSON array of Filters. See Filter descriptions below. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.qkeywordsoffsetoorderffilters_get_with_http_info(keyword, offset, order, filters, **kwargs)  # noqa: E501
        else:
            (data) = self.qkeywordsoffsetoorderffilters_get_with_http_info(keyword, offset, order, filters, **kwargs)  # noqa: E501
            return data

    def qkeywordsoffsetoorderffilters_get_with_http_info(self, keyword, offset, order, filters, **kwargs):  # noqa: E501
        """Search File Names  # noqa: E501

        Search file names of the uploaded documents in the OPIF system.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.qkeywordsoffsetoorderffilters_get_with_http_info(keyword, offset, order, filters, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str keyword: Keyword. (required)
        :param str offset: Search results starting number. (required)
        :param str order: Sorting parameter. (required)
        :param str filters: JSON array of Filters. See Filter descriptions below. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['keyword', 'offset', 'order', 'filters']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method qkeywordsoffsetoorderffilters_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'keyword' is set
        if ('keyword' not in params or
                params['keyword'] is None):
            raise ValueError("Missing the required parameter `keyword` when calling `qkeywordsoffsetoorderffilters_get`")  # noqa: E501
        # verify the required parameter 'offset' is set
        if ('offset' not in params or
                params['offset'] is None):
            raise ValueError("Missing the required parameter `offset` when calling `qkeywordsoffsetoorderffilters_get`")  # noqa: E501
        # verify the required parameter 'order' is set
        if ('order' not in params or
                params['order'] is None):
            raise ValueError("Missing the required parameter `order` when calling `qkeywordsoffsetoorderffilters_get`")  # noqa: E501
        # verify the required parameter 'filters' is set
        if ('filters' not in params or
                params['filters'] is None):
            raise ValueError("Missing the required parameter `filters` when calling `qkeywordsoffsetoorderffilters_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'keyword' in params:
            path_params['keyword'] = params['keyword']  # noqa: E501
        if 'offset' in params:
            path_params['offset'] = params['offset']  # noqa: E501
        if 'order' in params:
            path_params['order'] = params['order']  # noqa: E501
        if 'filters' in params:
            path_params['filters'] = params['filters']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            'q={keyword}&s={offset}&o={order}&f={filters}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
