# coding: utf-8

"""
    OPIF Service Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.service_api import ServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceApi(unittest.TestCase):
    """ServiceApi unit test stubs"""

    def setUp(self):
        self.api = api.service_api.ServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_service_type_applications_facility_entity_id_format_get(self):
        """Test case for service_type_applications_facility_entity_id_format_get

        Entity Applications  # noqa: E501
        """
        pass

    def test_service_type_eeo_facilityid_entity_id_format_get(self):
        """Test case for service_type_eeo_facilityid_entity_id_format_get

        Entity EEO  # noqa: E501
        """
        pass

    def test_service_type_facility_getall_format_get(self):
        """Test case for service_type_facility_getall_format_get

        Get All  # noqa: E501
        """
        pass

    def test_service_type_facility_id_entity_id_format_get(self):
        """Test case for service_type_facility_id_entity_id_format_get

        Entity Details  # noqa: E501
        """
        pass

    def test_service_type_ownership_facilityid_entity_id_format_get(self):
        """Test case for service_type_ownership_facilityid_entity_id_format_get

        Entity Ownership  # noqa: E501
        """
        pass

    def test_service_type_relationship_frn_frn_format_get(self):
        """Test case for service_type_relationship_frn_frn_format_get

        Relationship FRN  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
