# coding: utf-8

"""
    OPIF Service Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.contact_updates_api import ContactUpdatesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestContactUpdatesApi(unittest.TestCase):
    """ContactUpdatesApi unit test stubs"""

    def setUp(self):
        self.api = api.contact_updates_api.ContactUpdatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contact_update_json_post(self):
        """Test case for contact_update_json_post

        Specify contactType as \"MS\" for Main Studio Contact and \"CC\" for Closed Caption Contact.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
