# coding: utf-8

"""
    OPIF Service Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.relationship_api import RelationshipApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRelationshipApi(unittest.TestCase):
    """RelationshipApi unit test stubs"""

    def setUp(self):
        self.api = api.relationship_api.RelationshipApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_relationship_frn_frn_format_get(self):
        """Test case for relationship_frn_frn_format_get

        Relationship FRN  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
