# coding: utf-8

"""
    OPIF Service Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.file_restore_post import FileRestorePost  # noqa: E501
from swagger_client.rest import ApiException


class TestFileRestorePost(unittest.TestCase):
    """FileRestorePost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileRestorePost(self):
        """Test FileRestorePost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.file_restore_post.FileRestorePost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
