# coding: utf-8

"""
    OPIF Service Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.folder_history import FolderHistory  # noqa: E501
from swagger_client.rest import ApiException


class TestFolderHistory(unittest.TestCase):
    """FolderHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFolderHistory(self):
        """Test FolderHistory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.folder_history.FolderHistory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
