# coding: utf-8

"""
    OPIF Service Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.facility_api import FacilityApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFacilityApi(unittest.TestCase):
    """FacilityApi unit test stubs"""

    def setUp(self):
        self.api = api.facility_api.FacilityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_facility_search_keyword_format_get(self):
        """Test case for facility_search_keyword_format_get

        Search  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
