# coding: utf-8

"""
    OPIF Service Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.sdars_api import SdarsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSdarsApi(unittest.TestCase):
    """SdarsApi unit test stubs"""

    def setUp(self):
        self.api = api.sdars_api.SdarsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sdars_eeo_facility_facility_id_format_get(self):
        """Test case for sdars_eeo_facility_facility_id_format_get

        SDARS EEO  # noqa: E501
        """
        pass

    def test_sdars_frn_frn_format_get(self):
        """Test case for sdars_frn_frn_format_get

        SDARS Entity Details  # noqa: E501
        """
        pass

    def test_sdars_getall_format_get(self):
        """Test case for sdars_getall_format_get

        Get All  # noqa: E501
        """
        pass

    def test_sdars_licensee_address_update_json_post(self):
        """Test case for sdars_licensee_address_update_json_post

        Update licensee address  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
