# coding: utf-8

"""
    OPIF Service Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.cable_principal_address_update_post import CablePrincipalAddressUpdatePost  # noqa: E501
from swagger_client.rest import ApiException


class TestCablePrincipalAddressUpdatePost(unittest.TestCase):
    """CablePrincipalAddressUpdatePost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCablePrincipalAddressUpdatePost(self):
        """Test CablePrincipalAddressUpdatePost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cable_principal_address_update_post.CablePrincipalAddressUpdatePost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
