# coding: utf-8

"""
    OPIF Service Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.cable_operator_address_update_post import CableOperatorAddressUpdatePost  # noqa: E501
from swagger_client.rest import ApiException


class TestCableOperatorAddressUpdatePost(unittest.TestCase):
    """CableOperatorAddressUpdatePost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCableOperatorAddressUpdatePost(self):
        """Test CableOperatorAddressUpdatePost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cable_operator_address_update_post.CableOperatorAddressUpdatePost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
