# coding: utf-8

"""
    OPIF Service Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.cable_api import CableApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCableApi(unittest.TestCase):
    """CableApi unit test stubs"""

    def setUp(self):
        self.api = api.cable_api.CableApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cable_communities_psid_psid_format_get(self):
        """Test case for cable_communities_psid_psid_format_get

        Cable Communities  # noqa: E501
        """
        pass

    def test_cable_eeo_group_by_format_get(self):
        """Test case for cable_eeo_group_by_format_get

        Cable eeo  # noqa: E501
        """
        pass

    def test_cable_empunitid_update_json_post(self):
        """Test case for cable_empunitid_update_json_post

        Modify Cable service employee units  # noqa: E501
        """
        pass

    def test_cable_getall_format_get(self):
        """Test case for cable_getall_format_get

        Get All  # noqa: E501
        """
        pass

    def test_cable_operator_address_update_json_post(self):
        """Test case for cable_operator_address_update_json_post

        Modify Cable operator address  # noqa: E501
        """
        pass

    def test_cable_principal_address_update_json_post(self):
        """Test case for cable_principal_address_update_json_post

        Modify Cable principal address  # noqa: E501
        """
        pass

    def test_cable_psid_psid_format_get(self):
        """Test case for cable_psid_psid_format_get

        Cable Details  # noqa: E501
        """
        pass

    def test_cable_relationship_username_coalsid_format_get(self):
        """Test case for cable_relationship_username_coalsid_format_get

        Relationship Cable  # noqa: E501
        """
        pass

    def test_cable_service_zipcodes_update_json_post(self):
        """Test case for cable_service_zipcodes_update_json_post

        Modify Cable service zip codes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
