# coding: utf-8

"""
    OPIF Service Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.dbs_api import DbsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDbsApi(unittest.TestCase):
    """DbsApi unit test stubs"""

    def setUp(self):
        self.api = api.dbs_api.DbsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dbs_eeo_facility_facility_id_format_get(self):
        """Test case for dbs_eeo_facility_facility_id_format_get

        DBS EEO  # noqa: E501
        """
        pass

    def test_dbs_frn_frn_format_get(self):
        """Test case for dbs_frn_frn_format_get

        DBS Entity Details  # noqa: E501
        """
        pass

    def test_dbs_getall_format_get(self):
        """Test case for dbs_getall_format_get

        Get All  # noqa: E501
        """
        pass

    def test_dbs_licensee_address_update_json_post(self):
        """Test case for dbs_licensee_address_update_json_post

        Update licensee address  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
